#!/usr/bin/env bash

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/config.inc"

CONTAINER_ARGS="${@:1}"
#echo ">>>>>DOCKER:COMPOSER START [CMD: ${CONTAINER_ARGS}]
#"

docker run --rm -t -i \
    --net "${COMPOSE_NETWORK}" \
    --hostname=${PROJECT} \
    --volumes-from="${PROJECT}_source_1" \
    --volume="${PATH_APP}/scripts:/app/scripts" \
    --volume="${PATH_APP}/composer.json:/app/composer.json" \
    --volume="${PATH_HOME}/.gitconfig:/app/.gitconfig" \
    --volume="${PATH_HOME}/.ssh:/app/.ssh" \
    --entrypoint=composer \
    -w=/app \
    --name="${PROJECT}_composer" \
    --user=app \
    -e COMPOSER_PROCESS_TIMEOUT=600 \
    ${DOCKER_IMAGE_DEVELOPERTOOL} \
    --working-dir=/app \
    ${CONTAINER_ARGS}

#echo "
#<<<<<DOCKER:COMPOSER END "
