#!/usr/bin/env bash
# RUN docker-composer
#
# This is a wrapper around docker composer so that we can force a project name
# as a base for all container names, and so that we can allow switching of yml
# configurations files.
#

docker-compose --file "${COMPOSE_FILE}" --project-name "${COMPOSE_PROJECT_NAME}" $@
