#!/usr/bin/env bash
######
# Run gulp in a containter
#
# This script runs a command container, using gulp in a specifiec folder
#
# The container tries to run gulp $@ in a specified path, which should contain
# a gulpfile.
#
# Note that the folder must be in the app/ path, as this is mapped into 
# the container, at a predictable point:
#   host: ./app  -> container: /app/project
# So that any subpath is easily remapped:
#   host: ./app/web/themes/custom/MyTheme -> container: /app/project/web/themes/custom/MyTheme
#
# You can easily alter this, as long as you are aware of how files are
# mapped in the container.
#

# use the run path for execution
PATH_GULP="${PATH_EXECUTION}"

CONTAINER_ARGS="$@"
# echo ">>>>>DOCKER:GULP START [CMD: ${CONTAINER_ARGS}]
# "

exec docker run --rm -t -i \
    --net "${COMPOSE_NETWORK}" \
    --hostname="${PROJECT}" \
    --volume="${PATH_GULP}:${CONTAINER_PATH_APP}/gulptarget" \
    --entrypoint="/usr/bin/gulp" \
    -w="${CONTAINER_PATH_APP}/gulptarget" \
    --name="${PROJECT}_composer" \
    ${DOCKER_IMAGE_DEVELOPERTOOL} \
    ${CONTAINER_ARGS}

# echo "
# <<<<<DOCKER:GULP END "