#!/usr/bin/env bash
###
# Initialise a new Drupal 8 project.
#
# This command does the following:
#   - Uses Composer to create a Drupal 8 project from drupal-composer/drupal-project.
#   - Copies into place the default wundertools.settings.inc and compose-default.yml file.
#

printf "Initialising new Drupal 8 project (drupal-composer/drupal-project) in the current folder...\n"

"${PATH_WUNDERTOOLS}/wundertools" composer create-project drupal-composer/drupal-project:8.x-dev temp --stability dev --no-interaction
cd "${PATH_WUNDERTOOLS}/../temp"
cp -a . ../
cd ..
rm -rf temp

if [ ! -d "${PATH_WUNDERTOOLS}/../app" ]
then
  printf "Initialising app folder...\n"
  mkdir -p "${PATH_WUNDERTOOLS}/../app"
fi

printf "Initialising default settings...\n"

cp "${PATH_WUNDERTOOLS}/wundertools.settings.inc" "${PATH_WUNDERTOOLS}/../app"
cp "${PATH_WUNDERTOOLS}/compose-default.yml" "${PATH_WUNDERTOOLS}/../app"
