#!/usr/bin/env bash
####
# Shell
#
# Gives a user zsh shell, with all volumes mpp in, and all 
# containers linked, for typical ssh like behaviour.
#

CONTAINER_ARGS="$@"
# echo ">>>>>DOCKER:SHELL START [ARG#:$#][CMD: ${CONTAINER_ARGS}]---[$*]:[$0][$1][$2][$3]
# "

docker run --rm -t -i \
    --net "${COMPOSE_NETWORK}" \
    --hostname=${PROJECT} \
    --link="${PROJECT}_db_1:db.app" \
    --link="${PROJECT}_fpm_1:fpm.app" \
    --link="${PROJECT}_www_1:www.app" \
    --volumes-from="${PROJECT}_source_1" \
    --volume="${PATH_APP}:/app/project" \
    --volume="${PATH_SOURCE}:/app/source" \
    --volume="${PATH_SOURCE}/console:/app/.console" \
    --volume="${PATH_SOURCE}/drush:/app/.drush" \
    --volume="${PATH_HOME}/.gitconfig:/app/.gitconfig" \
    --volume="${PATH_HOME}/.ssh:/app/.ssh" \
    -w=/app \
    --name="${PROJECT}_shell" \
    --user=app \
    ${DOCKER_IMAGE_DEVELOPERTOOL} \
    ${CONTAINER_ARGS}

# echo "
# <<<<<DOCKER:SHELL END "
