#!/usr/bin/env bash

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../config.inc"

if [ -z "${COMPOSE_NETWORK}" ]; then
	FORMAT="{{ .NetworkSettings.IPAddress }}"
else
	FORMAT="{{ .NetworkSettings.Networks.${COMPOSE_NETWORK}.IPAddress }}"
fi

docker inspect --format "${FORMAT}" "${PROJECT}_${1}_1"
