#!/usr/bin/env bash

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/config.inc"

CONTAINER_ARGS="${@:1}"
#echo ">>>>>DOCKER:COMPOSER START [CMD: ${CONTAINER_ARGS}]
#"

docker run --rm -t -i \
    --net "${COMPOSE_NETWORK}" \
    --hostname=${PROJECT} \
    --volume="${PATH_APP}/web:/app/web" \
    --volume="${PATH_APP}/vendor:/app/vendor" \
    --volume="${PATH_APP}/scripts:/app/scripts" \
    --volume="${PATH_APP}/composer.json:/app/composer.json" \
    --volume="${PATH_HOME}/.gitconfig:/app/.gitconfig" \
    --volume="${PATH_HOME}/.ssh:/app/.ssh" \    
    --entrypoint=/usr/bin/composer \
    -w=/app/project \
    --name="${PROJECT}_composer" \
    jamesnesbitt/wunder-developershell \
    --working-dir=/app/project \
    ${CONTAINER_ARGS}

#echo "
#<<<<<DOCKER:COMPOSER END "
