#!/usr/bin/env bash
######
# Run gulp in a containter
#
# This script runs a command container, using gulp in a specifiec folder
#
# The container tries to run gulp $@ in a specified path, which should contain
# a gulpfile.
#
# Note that the folder must be in the app/ path, as this is mapped into 
# the container, at a predictable point:
#   host: ./app  -> container: /app/project
# So that any subpath is easily remapped:
#   host: ./app/web/themes/custom/MyTheme -> container: /app/project/web/themes/custom/MyTheme
#
# You can easily alter this, as long as you are aware of how files are
# mapped in the container.
#

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/config.inc"

PATH_GULP="${PATH_EXECUTION:-${PATH_APP}}"

CONTAINER_ARGS="${@:1}"
# echo ">>>>>DOCKER:GULP START [CMD: ${CONTAINER_ARGS}]
# "

docker run --rm -t -i \
    --net "${COMPOSE_NETWORK}" \
    --hostname=${PROJECT} \
    --volume="${PATH_GULP}:/app/project" \
    --entrypoint=/usr/bin/gulp \
    -w=/app/project \
    --name="${PROJECT}_composer" \
    ${DOCKER_IMAGE_DEVELOPERTOOL} \
    ${CONTAINER_ARGS}

# echo "
# <<<<<DOCKER:GULP END "