#!/usr/bin/env bash

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/config.inc"

CONTAINER_ARGS="${@:1}"
# echo ">>>>>DOCKER:SHELL START [ARG#:$#][CMD: ${CONTAINER_ARGS}]---[$*]:[$0][$1][$2][$3]
# "

docker run --rm -t -i \
    --net "${COMPOSE_NETWORK}" \
    --hostname=${PROJECT} \
    --link="${PROJECT}_db_1:db.app" \
    --link="${PROJECT}_fpm_1:fpm.app" \
    --link="${PROJECT}_www_1:www.app" \
    --volume="${PATH_APP}/web:/app/web" \
    --volume="${PATH_APP}/vendor:/app/vendor" \
    --volume="${PATH_APP}/scripts:/app/scripts" \
    --volume="${PATH_APP}/composer.json:/app/composer.json" \
    --volume="${PATH_APP}/console:/app/.console" \
    --volume="${PATH_APP}/drush:/app/.drush" \
    --volume="${PATH_HOME}/.ssh:/app/.ssh" \
    -w=/app \
    --name="${PROJECT}_shell" \
    --user=app \
    ${DOCKER_IMAGE_DEVELOPERTOOL} \
    ${CONTAINER_ARGS}

# echo "
# <<<<<DOCKER:SHELL END "
