#!/usr/bin/env bash

NODE="${1}"
if [ -z "${NODE}" ]; then
	echo "[- There was no node specified, did you want to check for 'containerIP www'? -]"
	exit 1
fi

# output a node IP for a network to screen
function outputContainerIP {
  local PROJECT=${1}
  local NODE=${2}
  local NETWORK=${3}

  IP="`getContainerIP ${PROJECT} ${NODE} ${NETWORK}`"
  case "${IP}" in
  	"")
      ;;
    "<no value>")
      ;;
    *)
      echo "${NODE}:${NETWORK:-default}: ${IP}"
      ;;
  esac
}

# retrieve a node IP
function getContainerIP {
  local PROJECT=${1}
  local NODE=${2}
  local NETWORK=${3}
  local FORMAT=""

  if [ -z "${NETWORK}" ]; then
	FORMAT="{{ .NetworkSettings.IPAddress }}"
  else 
	FORMAT="{{ .NetworkSettings.Networks.${PROJECT}_${NETWORK}.IPAddress }}"
  fi

  docker inspect --format "${FORMAT}" "${PROJECT}_${NODE}_1"
}



# DEFAULT NETWORK
outputContainerIP $PROJECT $NODE
# DEFAULT NETWORK
outputContainerIP $PROJECT $NODE "default"
# INTERNAL NETWORK
outputContainerIP $PROJECT $NODE "internal"
# BACKEND NETWORK
outputContainerIP $PROJECT $NODE "public"